name: "Build and Release Supa"

on:
  push:
    branches:
      - release
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
            name: "macOS (ARM64)"
          # - platform: "macos-latest"
          #   args: "--target x86_64-apple-darwin"
          #   name: "macOS (x86_64)"
          # - platform: "ubuntu-latest"
          #   args: ""
          #   name: "Linux"
          # - platform: "windows-latest"
          #   args: ""
          #   name: "Windows"

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
          toolchain: stable

      - name: Install root dependencies
        run: |
          # Install root dependencies
          npm install
          # Install client dependencies
          cd packages/client
          npm install
          # Install core dependencies
          cd ../core
          npm install

      - name: Install ttabs dependencies
        run: |
          cd packages/ttabs
          npm install
          cd packages/ttabs
          npm install

      - name: Install reptree dependencies
        run: |
          cd packages/reptree
          npm install

      - name: Build the application
        run: |
          cd packages/client
          npm run tauri build -- --verbose
        env:
          NODE_ENV: production

      - name: Create release and upload artifacts
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "Supa v__VERSION__"
          releaseBody: |
            ## What's Changed
            *Auto-generated release notes*
            
            ### Downloads
            See assets below for platform-specific builds.
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
